## Preprocessing

In [ ]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [ ]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop(['EIN', 'NAME'], axis=1)

In [ ]:
# Determine the number of unique values in each column.
unique_counts = application_df.nunique()
unique_counts

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [ ]:
# Look at APPLICATION_TYPE value counts for binning
application_counts = application_df['APPLICATION_TYPE'].value_counts()
application_counts

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [ ]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
cutoff_value = 500

# Create a list of application types to be replaced
application_types_to_replace = list(application_counts[application_counts < cutoff_value].index)

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [ ]:
# Look at CLASSIFICATION value counts for binning
classification_counts = application_df['CLASSIFICATION'].value_counts()
classification_counts

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [ ]:
# You may find it helpful to look at CLASSIFICATION value counts >1
classification_counts_greater_than_1 = classification_counts[classification_counts > 1]
classification_counts_greater_than_1

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [ ]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
cutoff_value = 100

# Create a list of classifications to be replaced
classifications_to_replace = list(classification_counts[classification_counts < cutoff_value].index)

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
Other      669
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
Name: CLASSIFICATION, dtype: int64

In [ ]:
# Convert categorical data to numeric with `pd.get_dummies`
application_df = pd.get_dummies(application_df, columns=['APPLICATION_TYPE', 'CLASSIFICATION'])
application_df

,AFFILIATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,...,CLASSIFICATION_C1270,CLASSIFICATION_C1700,CLASSIFICATION_C2000,CLASSIFICATION_C2100,CLASSIFICATION_C2700,CLASSIFICATION_C3000,CLASSIFICATION_C4000,CLASSIFICATION_C5000,CLASSIFICATION_C7000,CLASSIFICATION_Other
0,Independent,ProductDev,Association,1,0,N,5000,1,0,1,...,0,0,0,0,0,0,0,0,0,0
1,Independent,Preservation,Co-operative,1,1-9999,N,108590,1,0,0,...,0,0,1,0,0,0,0,0,0,0
2,CompanySponsored,ProductDev,Association,1,0,N,5000,0,0,0,...,0,0,0,0,0,1,0,0,0,0
3,CompanySponsored,Preservation,Trust,1,10000-24999,N,6692,1,0,0,...,0,0,1,0,0,0,0,0,0,0
4,Independent,Heathcare,Trust,1,100000-499999,N,142590,1,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,Independent,ProductDev,Association,1,0,N,5000,0,0,0,...,0,0,0,0,0,0,0,0,0,0
34295,CompanySponsored,ProductDev,Association,1,0,N,5000,0,0,0,...,0,0,0,0,0,1,0,0,0,0
34296,CompanySponsored,Preservation,Association,1,0,N,5000,0,0,0,...,0,0,1,0,0,0,0,0,0,0
34297,Independent,ProductDev,Association,1,0,N,5000,1,0,0,...,0,0,0,0,0,1,0,0,0,0
34298,Independent,Preservation,Co-operative,1,1M-5M,N,36500179,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
# Split our preprocessed data into our features and target arrays
X = application_df.drop('IS_SUCCESSFUL', axis=1)
y = application_df['IS_SUCCESSFUL']

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
import numpy as np
from sklearn.preprocessing import StandardScaler

# Create a StandardScaler instance
scaler = StandardScaler()

# Select only numeric columns
numeric_columns = X_train.select_dtypes(include=[np.number])

# Fit the StandardScaler to the numeric data
X_scaler = scaler.fit(numeric_columns)

# Scale the data
X_train_scaled = X_scaler.transform(numeric_columns)
X_test_scaled = X_scaler.transform(X_test.select_dtypes(include=[np.number]))

## Compile, Train and Evaluate the Model

In [ ]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=64, activation='relu', input_dim=X_train_scaled.shape[1]))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=32, activation='relu'))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# Check the structure of the model
nn.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_3 (Dense)             (None, 64)                1536

 dense_4 (Dense)             (None, 32)                2080

 dense_5 (Dense)             (None, 1)                 33

=================================================================
Total params: 3649 (14.25 KB)
Trainable params: 3649 (14.25 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [ ]:
# Compile the model
nn.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [ ]:
# Train the model
history = nn.fit(X_train_scaled, y_train, epochs=100, batch_size=128, validation_data=(X_test_scaled, y_test))

Epoch 1/100
215/215 [==============================] - 1s 3ms/step - loss: 0.6353 - accuracy: 0.6193 - val_loss: 0.6397 - val_accuracy: 0.6224
Epoch 2/100
215/215 [==============================] - 1s 3ms/step - loss: 0.6354 - accuracy: 0.6217 - val_loss: 0.6395 - val_accuracy: 0.6181
Epoch 3/100
215/215 [==============================] - 1s 3ms/step - loss: 0.6354 - accuracy: 0.6188 - val_loss: 0.6397 - val_accuracy: 0.6187
Epoch 4/100
215/215 [==============================] - 0s 2ms/step - loss: 0.6352 - accuracy: 0.6216 - val_loss: 0.6399 - val_accuracy: 0.6222
Epoch 5/100
215/215 [==============================] - 0s 2ms/step - loss: 0.6352 - accuracy: 0.6196 - val_loss: 0.6398 - val_accuracy: 0.6181
Epoch 6/100
215/215 [==============================] - 0s 2ms/step - loss: 0.6352 - accuracy: 0.6195 - val_loss: 0.6404 - val_accuracy: 0.6222
Epoch 7/100
215/215 [==============================] - 1s 3ms/step - loss: 0.6353 - accuracy: 0.6206 - val_loss: 0.6398 - val_accuracy: 0.6182
Epoch 8/100
215/215 [==============================] - 1s 4ms/step - loss: 0.6352 - accuracy: 0.6205 - val_loss: 0.6401 - val_accuracy: 0.6222
Epoch 9/100
215/215 [==============================] - 1s 3ms/step - loss: 0.6352 - accuracy: 0.6208 - val_loss: 0.6395 - val_accuracy: 0.6230
Epoch 10/100
215/215 [==============================] - 1s 4ms/step - loss: 0.6350 - accuracy: 0.6196 - val_loss: 0.6394 - val_accuracy: 0.6229
Epoch 11/100
215/215 [==============================] - 1s 2ms/step - loss: 0.6351 - accuracy: 0.6202 - val_loss: 0.6397 - val_accuracy: 0.6224
Epoch 12/100
215/215 [==============================] - 1s 2ms/step - loss: 0.6349 - accuracy: 0.6224 - val_loss: 0.6398 - val_accuracy: 0.6230
Epoch 13/100
215/215 [==============================] - 1s 3ms/step - loss: 0.6348 - accuracy: 0.6215 - val_loss: 0.6394 - val_accuracy: 0.6233
Epoch 14/100
215/215 [==============================] - 0s 2ms/step - loss: 0.6350 - accuracy: 0.6227 - val_loss: 0.6390 - val_accuracy: 0.6236
Epoch 15/100
215/215 [==============================] - 1s 2ms/step - loss: 0.6348 - accuracy: 0.6216 - val_loss: 0.6397 - val_accuracy: 0.6236
Epoch 16/100
215/215 [==============================] - 1s 3ms/step - loss: 0.6347 - accuracy: 0.6214 - val_loss: 0.6391 - val_accuracy: 0.6188
Epoch 17/100
215/215 [==============================] - 1s 3ms/step - loss: 0.6347 - accuracy: 0.6226 - val_loss: 0.6392 - val_accuracy: 0.6226
Epoch 18/100
215/215 [==============================] - 1s 3ms/step - loss: 0.6349 - accuracy: 0.6208 - val_loss: 0.6393 - val_accuracy: 0.6249
Epoch 19/100
215/215 [==============================] - 1s 2ms/step - loss: 0.6349 - accuracy: 0.6226 - val_loss: 0.6393 - val_accuracy: 0.6190
Epoch 20/100
215/215 [==============================] - 0s 2ms/step - loss: 0.6345 - accuracy: 0.6233 - val_loss: 0.6394 - val_accuracy: 0.6190
Epoch 21/100
215/215 [==============================] - 1s 3ms/step - loss: 0.6349 - accuracy: 0.6212 - val_loss: 0.6392 - val_accuracy: 0.6230
Epoch 22/100
215/215 [==============================] - 1s 3ms/step - loss: 0.6349 - accuracy: 0.6220 - val_loss: 0.6394 - val_accuracy: 0.6188
Epoch 23/100
215/215 [==============================] - 1s 3ms/step - loss: 0.6347 - accuracy: 0.6210 - val_loss: 0.6391 - val_accuracy: 0.6245
Epoch 24/100
215/215 [==============================] - 1s 3ms/step - loss: 0.6345 - accuracy: 0.6216 - val_loss: 0.6396 - val_accuracy: 0.6188
Epoch 25/100
215/215 [==============================] - 1s 2ms/step - loss: 0.6345 - accuracy: 0.6219 - val_loss: 0.6389 - val_accuracy: 0.6190
Epoch 26/100
215/215 [==============================] - 1s 3ms/step - loss: 0.6345 - accuracy: 0.6196 - val_loss: 0.6387 - val_accuracy: 0.6236
Epoch 27/100
215/215 [==============================] - 0s 2ms/step - loss: 0.6345 - accuracy: 0.6219 - val_loss: 0.6391 - val_accuracy: 0.6230
Epoch 28/100
215/215 [==============================] - 1s 2ms/step - loss: 0.6342 - accuracy: 0.6244 - val_loss: 0.6392 - val_accuracy: 0.6230
Epoch 29/100
215/215 [==============================] - 0s 2ms/step - loss: 0.6345 - accuracy: 0.6216 - val_loss: 0.6389 - val_accuracy: 0.6184
Epoch 30/100
215/215 [==============================] - 1s 3ms/step - loss: 0.6344 - accuracy: 0.6213 - val_loss: 0.6391 - val_accuracy: 0.6188
Epoch 31/100
215/215 [==============================] - 1s 3ms/step - loss: 0.6345 - accuracy: 0.6216 - val_loss: 0.6392 - val_accuracy: 0.6181
Epoch 32/100
215/215 [==============================] - 1s 3ms/step - loss: 0.6342 - accuracy: 0.6219 - val_loss: 0.6391 - val_accuracy: 0.6245
Epoch 33/100
215/215 [==============================] - 1s 4ms/step - loss: 0.6343 - accuracy: 0.6244 - val_loss: 0.6390 - val_accuracy: 0.6185
Epoch 34/100
215/215 [==============================] - 0s 2ms/step - loss: 0.6346 - accuracy: 0.6227 - val_loss: 0.6393 - val_accuracy: 0.6226
Epoch 35/100
215/215 [==============================] - 1s 3ms/step - loss: 0.6345 - accuracy: 0.6219 - val_loss: 0.6390 - val_accuracy: 0.6232
Epoch 36/100
215/215 [==============================] - 1s 3ms/step - loss: 0.6342 - accuracy: 0.6236 - val_loss: 0.6394 - val_accuracy: 0.6185
Epoch 37/100
215/215 [==============================] - 1s 3ms/step - loss: 0.6342 - accuracy: 0.6237 - val_loss: 0.6389 - val_accuracy: 0.6230
Epoch 38/100
215/215 [==============================] - 0s 2ms/step - loss: 0.6343 - accuracy: 0.6231 - val_loss: 0.6388 - val_accuracy: 0.6233
Epoch 39/100
215/215 [==============================] - 1s 2ms/step - loss: 0.6344 - accuracy: 0.6236 - val_loss: 0.6391 - val_accuracy: 0.6229
Epoch 40/100
215/215 [==============================] - 1s 2ms/step - loss: 0.6343 - accuracy: 0.6229 - val_loss: 0.6392 - val_accuracy: 0.6224
Epoch 41/100
215/215 [==============================] - 0s 2ms/step - loss: 0.6341 - accuracy: 0.6214 - val_loss: 0.6386 - val_accuracy: 0.6241
Epoch 42/100
215/215 [==============================] - 1s 3ms/step - loss: 0.6342 - accuracy: 0.6240 - val_loss: 0.6393 - val_accuracy: 0.6185
Epoch 43/100
215/215 [==============================] - 0s 2ms/step - loss: 0.6341 - accuracy: 0.6215 - val_loss: 0.6387 - val_accuracy: 0.6188
Epoch 44/100
215/215 [==============================] - 1s 2ms/step - loss: 0.6340 - accuracy: 0.6233 - val_loss: 0.6396 - val_accuracy: 0.6184
Epoch 45/100
215/215 [==============================] - 1s 2ms/step - loss: 0.6342 - accuracy: 0.6235 - val_loss: 0.6390 - val_accuracy: 0.6184
Epoch 46/100
215/215 [==============================] - 1s 3ms/step - loss: 0.6341 - accuracy: 0.6245 - val_loss: 0.6391 - val_accuracy: 0.6185
Epoch 47/100
215/215 [==============================] - 0s 2ms/step - loss: 0.6339 - accuracy: 0.6218 - val_loss: 0.6386 - val_accuracy: 0.6229
Epoch 48/100
215/215 [==============================] - 1s 2ms/step - loss: 0.6339 - accuracy: 0.6238 - val_loss: 0.6395 - val_accuracy: 0.6232
Epoch 49/100
215/215 [==============================] - 1s 2ms/step - loss: 0.6340 - accuracy: 0.6231 - val_loss: 0.6388 - val_accuracy: 0.6222
Epoch 50/100
215/215 [==============================] - 1s 2ms/step - loss: 0.6341 - accuracy: 0.6220 - val_loss: 0.6388 - val_accuracy: 0.6233
Epoch 51/100
215/215 [==============================] - 1s 2ms/step - loss: 0.6340 - accuracy: 0.6228 - val_loss: 0.6386 - val_accuracy: 0.6219
Epoch 52/100
215/215 [==============================] - 0s 2ms/step - loss: 0.6341 - accuracy: 0.6230 - val_loss: 0.6391 - val_accuracy: 0.6226
Epoch 53/100
215/215 [==============================] - 1s 3ms/step - loss: 0.6338 - accuracy: 0.6224 - val_loss: 0.6392 - val_accuracy: 0.6182
Epoch 54/100
215/215 [==============================] - 1s 3ms/step - loss: 0.6338 - accuracy: 0.6232 - val_loss: 0.6396 - val_accuracy: 0.6185
Epoch 55/100
215/215 [==============================] - 1s 4ms/step - loss: 0.6340 - accuracy: 0.6241 - val_loss: 0.6394 - val_accuracy: 0.6222
Epoch 56/100
215/215 [==============================] - 1s 4ms/step - loss: 0.6339 - accuracy: 0.6227 - val_loss: 0.6395 - val_accuracy: 0.6173
Epoch 57/100
215/215 [==============================] - 1s 3ms/step - loss: 0.6340 - accuracy: 0.6217 - val_loss: 0.6392 - val_accuracy: 0.6220
Epoch 58/100
215/215 [==============================] - 1s 3ms/step - loss: 0.6339 - accuracy: 0.6227 - val_loss: 0.6388 - val_accuracy: 0.6230
Epoch 59/100
215/215 [==============================] - 1s 2ms/step - loss: 0.6338 - accuracy: 0.6239 - val_loss: 0.6388 - val_accuracy: 0.6224
Epoch 60/100
215/215 [==============================] - 0s 2ms/step - loss: 0.6340 - accuracy: 0.6220 - val_loss: 0.6395 - val_accuracy: 0.6211
Epoch 61/100
215/215 [==============================] - 1s 3ms/step - loss: 0.6340 - accuracy: 0.6227 - val_loss: 0.6387 - val_accuracy: 0.6227
Epoch 62/100
215/215 [==============================] - 1s 3ms/step - loss: 0.6336 - accuracy: 0.6237 - val_loss: 0.6394 - val_accuracy: 0.6175
Epoch 63/100
215/215 [==============================] - 0s 2ms/step - loss: 0.6340 - accuracy: 0.6231 - val_loss: 0.6393 - val_accuracy: 0.6182
Epoch 64/100
215/215 [==============================] - 0s 2ms/step - loss: 0.6341 - accuracy: 0.6204 - val_loss: 0.6392 - val_accuracy: 0.6233
Epoch 65/100
215/215 [==============================] - 0s 2ms/step - loss: 0.6340 - accuracy: 0.6247 - val_loss: 0.6391 - val_accuracy: 0.6227
Epoch 66/100
215/215 [==============================] - 1s 2ms/step - loss: 0.6339 - accuracy: 0.6238 - val_loss: 0.6389 - val_accuracy: 0.6220
Epoch 67/100
215/215 [==============================] - 1s 2ms/step - loss: 0.6339 - accuracy: 0.6233 - val_loss: 0.6390 - val_accuracy: 0.6185
Epoch 68/100
215/215 [==============================] - 0s 2ms/step - loss: 0.6340 - accuracy: 0.6228 - val_loss: 0.6384 - val_accuracy: 0.6236
Epoch 69/100
215/215 [==============================] - 0s 2ms/step - loss: 0.6337 - accuracy: 0.6228 - val_loss: 0.6387 - val_accuracy: 0.6235
Epoch 70/100
215/215 [==============================] - 0s 2ms/step - loss: 0.6337 - accuracy: 0.6236 - val_loss: 0.6387 - val_accuracy: 0.6229
Epoch 71/100
215/215 [==============================] - 1s 3ms/step - loss: 0.6338 - accuracy: 0.6226 - val_loss: 0.6397 - val_accuracy: 0.6230
Epoch 72/100
215/215 [==============================] - 1s 3ms/step - loss: 0.6337 - accuracy: 0.6252 - val_loss: 0.6391 - val_accuracy: 0.6169
Epoch 73/100
215/215 [==============================] - 0s 2ms/step - loss: 0.6338 - accuracy: 0.6230 - val_loss: 0.6388 - val_accuracy: 0.6223
Epoch 74/100
215/215 [==============================] - 1s 2ms/step - loss: 0.6339 - accuracy: 0.6222 - val_loss: 0.6392 - val_accuracy: 0.6230
Epoch 75/100
215/215 [==============================] - 1s 3ms/step - loss: 0.6336 - accuracy: 0.6242 - val_loss: 0.6392 - val_accuracy: 0.6230
Epoch 76/100
215/215 [==============================] - 1s 4ms/step - loss: 0.6338 - accuracy: 0.6224 - val_loss: 0.6397 - val_accuracy: 0.6226
Epoch 77/100
215/215 [==============================] - 1s 4ms/step - loss: 0.6337 - accuracy: 0.6233 - val_loss: 0.6395 - val_accuracy: 0.6172
Epoch 78/100
215/215 [==============================] - 1s 3ms/step - loss: 0.6340 - accuracy: 0.6233 - val_loss: 0.6404 - val_accuracy: 0.6206
Epoch 79/100
215/215 [==============================] - 1s 3ms/step - loss: 0.6337 - accuracy: 0.6228 - val_loss: 0.6388 - val_accuracy: 0.6232
Epoch 80/100
215/215 [==============================] - 1s 2ms/step - loss: 0.6339 - accuracy: 0.6249 - val_loss: 0.6396 - val_accuracy: 0.6220
Epoch 81/100
215/215 [==============================] - 0s 2ms/step - loss: 0.6338 - accuracy: 0.6240 - val_loss: 0.6390 - val_accuracy: 0.6227
Epoch 82/100
215/215 [==============================] - 1s 2ms/step - loss: 0.6334 - accuracy: 0.6234 - val_loss: 0.6391 - val_accuracy: 0.6181
Epoch 83/100
215/215 [==============================] - 1s 3ms/step - loss: 0.6338 - accuracy: 0.6235 - val_loss: 0.6389 - val_accuracy: 0.6229
Epoch 84/100
215/215 [==============================] - 1s 3ms/step - loss: 0.6336 - accuracy: 0.6225 - val_loss: 0.6393 - val_accuracy: 0.6223
Epoch 85/100
215/215 [==============================] - 0s 2ms/step - loss: 0.6336 - accuracy: 0.6227 - val_loss: 0.6391 - val_accuracy: 0.6223
Epoch 86/100
215/215 [==============================] - 0s 2ms/step - loss: 0.6335 - accuracy: 0.6221 - val_loss: 0.6395 - val_accuracy: 0.6206
Epoch 87/100
215/215 [==============================] - 1s 3ms/step - loss: 0.6337 - accuracy: 0.6238 - val_loss: 0.6392 - val_accuracy: 0.6224
Epoch 88/100
215/215 [==============================] - 1s 2ms/step - loss: 0.6336 - accuracy: 0.6242 - val_loss: 0.6399 - val_accuracy: 0.6169
Epoch 89/100
215/215 [==============================] - 1s 2ms/step - loss: 0.6336 - accuracy: 0.6243 - val_loss: 0.6388 - val_accuracy: 0.6222
Epoch 90/100
215/215 [==============================] - 1s 3ms/step - loss: 0.6336 - accuracy: 0.6243 - val_loss: 0.6396 - val_accuracy: 0.6168
Epoch 91/100
215/215 [==============================] - 1s 3ms/step - loss: 0.6336 - accuracy: 0.6239 - val_loss: 0.6391 - val_accuracy: 0.6236
Epoch 92/100
215/215 [==============================] - 1s 3ms/step - loss: 0.6337 - accuracy: 0.6233 - val_loss: 0.6395 - val_accuracy: 0.6181
Epoch 93/100
215/215 [==============================] - 1s 2ms/step - loss: 0.6336 - accuracy: 0.6229 - val_loss: 0.6396 - val_accuracy: 0.6210
Epoch 94/100
215/215 [==============================] - 0s 2ms/step - loss: 0.6338 - accuracy: 0.6233 - val_loss: 0.6390 - val_accuracy: 0.6184
Epoch 95/100
215/215 [==============================] - 1s 2ms/step - loss: 0.6335 - accuracy: 0.6220 - val_loss: 0.6389 - val_accuracy: 0.6187
Epoch 96/100
215/215 [==============================] - 1s 3ms/step - loss: 0.6334 - accuracy: 0.6245 - val_loss: 0.6393 - val_accuracy: 0.6184
Epoch 97/100
215/215 [==============================] - 1s 2ms/step - loss: 0.6334 - accuracy: 0.6235 - val_loss: 0.6429 - val_accuracy: 0.6146
Epoch 98/100
215/215 [==============================] - 1s 4ms/step - loss: 0.6337 - accuracy: 0.6232 - val_loss: 0.6391 - val_accuracy: 0.6227
Epoch 99/100
215/215 [==============================] - 1s 3ms/step - loss: 0.6336 - accuracy: 0.6239 - val_loss: 0.6389 - val_accuracy: 0.6216
Epoch 100/100
215/215 [==============================] - 1s 3ms/step - loss: 0.6336 - accuracy: 0.6224 - val_loss: 0.6392 - val_accuracy: 0.6230

In [ ]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

215/215 - 0s - loss: 0.6392 - accuracy: 0.6230 - 286ms/epoch - 1ms/step
Loss: 0.6391781568527222, Accuracy: 0.6230320930480957

In [ ]:
# Export our model to HDF5 file

nn.save("charity_model.h5")